.Dd October 19, 2025
.Dt STAGIT-HOOK 1
.Os
.Sh NAME
.Nm stagit-hook
.Nd Git hook to automatically run stagit
.Sh SYNOPSIS
.Nm
.Op Ar repo ...
.Sh DESCRIPTION
The 
.Nm
utility generates repository pages with
.Xr stagit 1
and repository index pages with
.Xr stagit-index 1 .
When used without arguments,
.Nm
determines the repository pages to generate with the
.Ev GIT_DIR
environment variable.
If
.Ev GIT_DIR
isn't set, it only generates an index page.
.Pp
If the
.Ic styledir
configuration option is set, styles are also updated.
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/stagit-hook
.Xr stagit-hook 5
configuration file.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Pp
Manually initialize
repository and index pages for
.Pa example :
.Pp
.Dl $ stagit-hook example
.Pp
Setup stagit-hook for all repositories with the
.Pa git-daemon-export-ok
file:
.Bd -offset indent -literal
$ mkdir -p ~/.git/hooks
$ echo '#!/bin/sh
test -e "$GIT_DIR"/git-daemon-export-ok &&
	exec stagit-hook' > ~/.git/hooks/post-update
$ chmod +x ~/.git/hooks/post-update
$ git config --global core.hooksPath ~/.git/hooks
$ doas sh -c 'echo hasfile git-daemon-export-ok > /etc/stagit-hook'
.El
.Sh SEE ALSO
.Xr stagit 1 ,
.Xr stagit-index 1 ,
.Xr githooks 5 ,
.Xr stagit-hook 5
.Sh AUTHORS
.An Jacob R. Edwards Aq Mt jacob@jacobedwards.org
