.Dd October 19, 2025
.Dt STAGIT-HOOK 5
.Os
.Sh NAME
.Nm stagit-hook
.Nd stagit-hook configuration file
.Sh DESCRIPTION
The
.Nm
configuration file contains various options for
.Xr stagit-hook 1 .
The options are listed below:
.Bl -tag -width Ds
.It Ic baseurl Ar url
Set the base url for
.Xr stagit 1 .
Defaults to
.Qq https://$(hostname)/projects/ .
.It Ic basedir Ar directory
Set the root for generated pages.
Defaults to
.Qq /var/www/htdocs/$(hostname)/projects/ .
.It Ic repodir Ar directory
Set the repository directory for generating the index.
Defaults to the home directory.
.It Ic hasfile Ar path
Specifies the file that repositories must contain to be indexed.
Defaults to
.Qq refs .
.El
.Bl -tag -width Ds
.It Ic styledir Ar path
Use the
.Pa favicon.png ,
.Pa logo.png ,
and
.Pa style.css
files from
.Ar path
to style repository and index pages as described in
.Xr stagit 1
and
.Xr stagit-index 1 .
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/stagit-hook
Contains configuration data for
.Xr stagit-hook 1 .
.El
.Sh EXAMPLES
Here is an example
.Pa /etc/stagit-hook :
.Bd -offset indent -literal
baseurl https://example.com/git
basedir /var/www/htdocs/example.com/git
hasfile git-daemon-export-ok
.Ed
.Sh SEE ALSO
.Xr stagit 1 ,
.Xr stagit-hook 1 ,
.Xr stagit-index 1
.Sh AUTHORS
.An Jacob R. Edwards Aq Mt jacob@jacobedwards.org
